# Copyright (C) 2012-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/c1lgt/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/c1lgt/proprietary/bin/glgps:system/bin/glgps \
    vendor/samsung/c1lgt/proprietary/lib/hw/gps.exynos4.vendor.so:system/lib/hw/gps.exynos4.vendor.so \
    vendor/samsung/c1lgt/proprietary/lib/hw/sensors.smdk4x12.so:system/lib/hw/sensors.smdk4x12.so \
    vendor/samsung/c1lgt/proprietary/lib/libakm.so:system/lib/libakm.so \
    vendor/samsung/c1lgt/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/c1lgt/proprietary/lib/libfimc.so:system/lib/libfimc.so \
    vendor/samsung/c1lgt/proprietary/lib/libfimg.so:system/lib/libfimg.so \
    vendor/samsung/c1lgt/proprietary/lib/libhwconverter.so:system/lib/libhwconverter.so \
    vendor/samsung/c1lgt/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/c1lgt/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/c1lgt/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/c1lgt/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/c1lgt/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/c1lgt/proprietary/priv-app/CellBroadcastReceiver/CellBroadcastReceiver.apk:system/priv-app/CellBroadcastReceiver/CellBroadcastReceiver.apk \
    vendor/samsung/c1lgt/proprietary/vendor/firmware/SlimISP_BK.bin:system/vendor/firmware/SlimISP_BK.bin \
    vendor/samsung/c1lgt/proprietary/vendor/firmware/SlimISP_GJ.bin:system/vendor/firmware/SlimISP_GJ.bin \
    vendor/samsung/c1lgt/proprietary/vendor/firmware/SlimISP_GM.bin:system/vendor/firmware/SlimISP_GM.bin \
    vendor/samsung/c1lgt/proprietary/vendor/firmware/SlimISP_PH.bin:system/vendor/firmware/SlimISP_PH.bin \
    vendor/samsung/c1lgt/proprietary/vendor/firmware/SlimISP_WH.bin:system/vendor/firmware/SlimISP_WH.bin \
    vendor/samsung/c1lgt/proprietary/vendor/firmware/SlimISP_ZD.bin:system/vendor/firmware/SlimISP_ZD.bin \
    vendor/samsung/c1lgt/proprietary/vendor/firmware/SlimISP_ZH.bin:system/vendor/firmware/SlimISP_ZH.bin \
    vendor/samsung/c1lgt/proprietary/vendor/firmware/SlimISP_ZK.bin:system/vendor/firmware/SlimISP_ZK.bin \
    vendor/samsung/c1lgt/proprietary/vendor/firmware/SlimISP_ZM.bin:system/vendor/firmware/SlimISP_ZM.bin \
    vendor/samsung/c1lgt/proprietary/vendor/lib/drm/libdrmwvmplgin.so:vendor/lib/drm/libdrmwvmplugin.so
